/********************************************************************
* ./bonsai/WCSimBonsaiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./bonsai/WCSimBonsaiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWCSimBonsaiDict();
extern void G__cpp_setup_inheritanceWCSimBonsaiDict();
extern void G__cpp_setup_typetableWCSimBonsaiDict();
extern void G__cpp_setup_memvarWCSimBonsaiDict();
extern void G__cpp_setup_globalWCSimBonsaiDict();
extern void G__cpp_setup_memfuncWCSimBonsaiDict();
extern void G__cpp_setup_funcWCSimBonsaiDict();
extern void G__set_cpp_environmentWCSimBonsaiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WCSimBonsai.hh"
#include "WCSimRootGeom.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WCSimBonsaiDictLN_TClass;
extern G__linked_taginfo G__WCSimBonsaiDictLN_TBuffer;
extern G__linked_taginfo G__WCSimBonsaiDictLN_TMemberInspector;
extern G__linked_taginfo G__WCSimBonsaiDictLN_TObject;
extern G__linked_taginfo G__WCSimBonsaiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WCSimBonsaiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCSimBonsaiDictLN_TClonesArray;
extern G__linked_taginfo G__WCSimBonsaiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WCSimBonsaiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCSimBonsaiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WCSimBonsaiDictLN_WCSimRootPMT;
extern G__linked_taginfo G__WCSimBonsaiDictLN_WCSimRootGeom;
extern G__linked_taginfo G__WCSimBonsaiDictLN_WCSimBonsai;

/* STUB derived class for protected member access */
